### ISSUE TITLE
QR Code for node info

### ISSUE THREAD

**Issue by ekerstein** [LightningK0ala/satoshis.place#1]
Might want to add a QR code for node info to the submit page. This will make it easier to open directly channels on mobile LN wallets.

**Comment by jcsmesquita** [comment]
This is good idea 🎈

**Comment by LightningK0ala** [comment]
Done, thanks for the suggestion! 🚀 

<img width="634" alt="screen shot 2018-06-25 at 5 43 13 pm" src="https://user-images.githubusercontent.com/40227301/41860624-614e0670-789f-11e8-889b-1c6615c5bd8d.png">
