### ISSUE TITLE
[suggestion] Encourage creativity / pixel art & reduce spam?

### ISSUE THREAD

**Issue by Tucsky** [LightningK0ala/satoshis.place#5]
I really like the projet... but I feel like the API does not really contribute to quality content on the board, is it ? :worried:
Also if you remove the ability to draw when you are far (zoomed out) you fix the dust spam issue.

I know its just a lightning demo but thought it could be improved :wink:

**Comment by LightningK0ala** [comment]
Hi @Tucsky, thanks for the suggestions! This is definitely a topic which I'm open to discuss with the community and have been thinking about myself.

The easiest solution would be to close the API from the public by adding a CORS policy that would only allow requests from the client app. Your suggestion to disable drawing from a distance is also a good one.

I intentionally left the API open (and eventually documented it) mainly for 2 reasons:
- Watch how bots + spam evolved and see how micro transactions can solve the spam problem by attributing a small economic cost (à là [hashcash](https://en.wikipedia.org/wiki/Hashcash) by Adam Back). Granted the total cost to paint the board is probably too low (~60 usd) at the moment to really see this effect, but the idea is we could watch this dynamic play out if satoshis.place can live another 2-3 years and we enter another bull market.
- Explore the ability for Lapp ecosystems to flourish. Apps which can interact with each other and monetize themselves in a permission-less fashion.

I think at this point it wouldn't be fair on developers who have already built / are building scripts + bots + services to simply cut API access. I'd like to hear more opinions on this matter and if you have any thoughts on those 2 points I mentioned do share them :)

**Comment by LightningK0ala** [comment]
The source code is open source now. Anyone can try experimental features now!
