### ISSUE TITLE
Not receiving payment requests from testnet

### ISSUE THREAD

**Issue by kikoncuo** [LightningK0ala/satoshis.place#8]
Yesterday my bot was receiving payment requests from testnet.satoshis.place.
Today, I'm not receiving any NEW_ORDER_RESULT events.
It seems to work when using the mainnet's API

![image](https://user-images.githubusercontent.com/9364584/53244107-c5f03880-36a1-11e9-8166-5853b3cebd09.png)

**Comment by LightningK0ala** [comment]
Sorry for the delay! Testnet is not available anymore #RECKLESS
